[package]
name = "rust_graph_theory"
version = "0.1.0"
authors = ["Fabio Cardoso <slynrick@gmail.com>"]
edition = "2018"

[dependencies]
rocket = "0.4.0"
serde = "1.0.39"
serde_json = "1.0.39"
serde_derive = "1.0.39"
rocket_cors = "0.4.0"